name: Build KernelSU For OnePlus6(enchilada)

on:
  workflow_dispatch:

jobs:
  KernelForEnchilada:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/SummerComings/android_kernel_oneplus_sdm845 --depth=1 -b ksu --recurse-submodules
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002 --depth=1 --single-branch --no-tags -b 12.0 ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
      - name: Compiling Kernel
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd android_kernel_oneplus_sdm845
          git submodule update --remote --recursive
          make O="$output_dir" \
                      sdm845-perf_defconfig \
                      enchilada_defconfig
          make -j $(nproc) \
                       O="$output_dir" \
                       CC=clang
          popd
      - name: Creating Config Info
        run: |
          pushd android_kernel_oneplus_sdm845
          echo "Device: OnePlus 6
          Code: enchilada
          Build KernelSU Version: $(($(git rev-list --count HEAD)+10200))
          Only For crdroidandroid(13.0)
          Kernel For OnePlus 6" >> INFO.txt
          popd
          
      - name: Upload File
        run : |
          mv android_kernel_oneplus_sdm845/out/arch/arm64/boot/Image.gz-dtb anykernel/
          cd anykernel
          zip -r ../anykernel-enchilada_4.9.337.zip *
          

      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: anykernel-enchilada_4.9.337.zip
          name: " OnePlus6-KernelSU_crdroidandroid13.0"
          tag: " ${{ github.run_number }}_OnePlus-KernelSU_crdroidandroid13.0"
          bodyFile: "INFO.txt"
          token: ${{ secrets.TOKEN }}
