name: debugger-action
on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      
      - name: Upload Zip Files
        uses: actions/upload-artifact@v3
        with:
          name: Source
          path: Source.zip
