name: debugger-action
on:
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Download and package
       run: |
          sudo apt install repo
          mkdir android-kernel && cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b android-msm-bonito-4.9-android12L
          repo sync
          zip -r ../Soucre.zip ./repo
         
      
     - name: Upload Zip Files
       uses: actions/upload-artifact@v3
       with:
        name: Source
        path: Source.zip
