# action 名
name: ssh
on:
  push:
    # 在如下分支的 push 事件触发时，执行 jobs
    branches: [ "master" ]

  # 开启可以手动执行 action，不想开启可以删掉下面这行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       - name: Setup Debug Session
#         uses: csexton/debugger-action@master

      - name: Upload Toolchain Tools
        run: |
          sudo apt install repo
          sudo git config --global user.name "SummerComings"
          sudo git config --global user.email "ji0644253@gmail.com"
          sudo mkdir android-kernel && cd android-kernel
          sudo repo init -u https://android.googlesource.com/kernel/manifest -b common-android-4.9
          sudo repo sync
  
      - name: Upload android-kernel
        uses: actions/upload-artifact@v3
        with:
          name: android-kernel
          path: android-kernel
