name: gitee update CI

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run update script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
