name: gitee update CI

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run update script
        run: |
          sudo mkdir ~/.ssh
          echo "${{secrets.GITEEKEY}}" > ~/.ssh/id_rsa
          git update-index --chmod=400 ~/.ssh/id_rsa
          git clone git@gitee.com:SummerComings/my-config.git
          cd my-config
          echo "yuy1" > yuy
          git add .
          git commit -m "update file"
          git push origin master
